/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */







declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  AdminUser: { // root type
    created_at: string; // String!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    password: string; // String!
    reset_password_token?: string | null; // String
    reset_passwotd_token_expires?: string | null; // String
    surname: string; // String!
    updated_at: string; // String!
    verification_token?: string | null; // String
    verification_token_expires?: string | null; // String
    verified: boolean; // Boolean!
  }
  AuthType: { // root type
    admin_user: NexusGenRootTypes['AdminUser']; // AdminUser!
    token: string; // String!
  }
  Mutation: {};
  Product: { // root type
    created_at: string; // String!
    creatorId: number; // Int!
    id: number; // Int!
    name: string; // String!
    price: number; // Float!
    updated_at: string; // String!
  }
  Query: {};
  User: { // root type
    email: string; // String!
    password: string; // String!
    username: string; // String!
  }
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  AdminUser: { // field return type
    created_at: string; // String!
    email: string; // String!
    id: number; // Int!
    name: string; // String!
    password: string; // String!
    reset_password_token: string | null; // String
    reset_passwotd_token_expires: string | null; // String
    surname: string; // String!
    updated_at: string; // String!
    verification_token: string | null; // String
    verification_token_expires: string | null; // String
    verified: boolean; // Boolean!
  }
  AuthType: { // field return type
    admin_user: NexusGenRootTypes['AdminUser']; // AdminUser!
    token: string; // String!
  }
  Mutation: { // field return type
    createAdminUserMutation: NexusGenRootTypes['AdminUser']; // AdminUser!
    createProductMutation: NexusGenRootTypes['Product']; // Product!
    login: NexusGenRootTypes['AuthType']; // AuthType!
  }
  Product: { // field return type
    createdBy: NexusGenRootTypes['User'] | null; // User
    created_at: string; // String!
    creatorId: number; // Int!
    id: number; // Int!
    name: string; // String!
    price: number; // Float!
    updated_at: string; // String!
  }
  Query: { // field return type
    getAdminUserQuery: NexusGenRootTypes['AdminUser']; // AdminUser!
    getAllAdminUserQuery: NexusGenRootTypes['AdminUser']; // AdminUser!
    products: NexusGenRootTypes['Product'][]; // [Product!]!
  }
  User: { // field return type
    email: string; // String!
    password: string; // String!
    username: string; // String!
  }
}

export interface NexusGenFieldTypeNames {
  AdminUser: { // field return type name
    created_at: 'String'
    email: 'String'
    id: 'Int'
    name: 'String'
    password: 'String'
    reset_password_token: 'String'
    reset_passwotd_token_expires: 'String'
    surname: 'String'
    updated_at: 'String'
    verification_token: 'String'
    verification_token_expires: 'String'
    verified: 'Boolean'
  }
  AuthType: { // field return type name
    admin_user: 'AdminUser'
    token: 'String'
  }
  Mutation: { // field return type name
    createAdminUserMutation: 'AdminUser'
    createProductMutation: 'Product'
    login: 'AuthType'
  }
  Product: { // field return type name
    createdBy: 'User'
    created_at: 'String'
    creatorId: 'Int'
    id: 'Int'
    name: 'String'
    price: 'Float'
    updated_at: 'String'
  }
  Query: { // field return type name
    getAdminUserQuery: 'AdminUser'
    getAllAdminUserQuery: 'AdminUser'
    products: 'Product'
  }
  User: { // field return type name
    email: 'String'
    password: 'String'
    username: 'String'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    createAdminUserMutation: { // args
      email: string; // String!
      name: string; // String!
      password: string; // String!
      surname: string; // String!
    }
    createProductMutation: { // args
      name: string; // String!
      price: number; // Float!
    }
    login: { // args
      email: string; // String!
      password: string; // String!
    }
  }
  Query: {
    getAdminUserQuery: { // args
      id: number; // Int!
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: any;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}