import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./_trpc/Provider";
import { getServerSession } from "next-auth";
import SessionProvider from "./_component/sessionProvider";
import Nav from "./_component/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <SessionProvider session={session}>
            <Nav />
            {children}
          </SessionProvider>
        </Provider>
      </body>
    </html>
  );
}
